### ISSUE TITLE
Define API routes

### ISSUE THREAD

**Issue by lutzzdias** [CaueMaldonadoLima/Manett#1]
Define which API routes should exist in order to create them within the `app/api` folder and start implementing functionality

**Comment by lutzzdias** [comment]
Since this is an open source project, I think that the readme or a `docs.md` file would make sense, keeping all of the "functional requirements" in one place would keep things simple and text-based would allow git to keep track of changes (just like we do with code)

**Comment by CaueMaldonadoLima** [comment]
I'm currently working on a README. I'll be updating it soon. Thanks for the advice!
